parserOptions:
   ecmaVersion: 10
   sourceType: module
   ecmaFeatures:
      jsx: true
env:
   es6: true
   browser: true
extends:
   - prettier
   - eslint:recommended
   - plugin:react/recommended
plugins:
   - prettier
   - react
   - react-hooks
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  prettier/prettier:
    - error
    - singleQuote: true

   